### ISSUE TITLE
Default artifact splitting rules need to be implemented in YBD

### ISSUE THREAD

**Issue by gtristan** [devcurmudgeon/ybd#145]
Currently only chunks which specifically declare their artifacts get split into separate artifacts (afaict), there are however defaults for splitting all other artifacts.

Lack of this leads to confusion as spotted here:
    https://gerrit.baserock.org/#/c/1693/

...where system-integration is currently specified to have specifically named thingamajiggies (for lack of a better word and impatience to find one :) )

**Comment by devcurmudgeon** [comment]
@nowster did some work on this, but it was reverted at c3567f41dfb1b01d356ad319fac6e70864744a92

ybd creates one artefact per chunk, which i think is better for most use-cases than morph's n-artifacts per chunk. i believe the best way to address the requirement is at system creation time (only include the necessary subset for each chunk, stratum).

there's also the use-case of 'deploying' just a single chunk to think about... maybe we should have a separate issue for that.

**Comment by rdale** [comment]
nowster's branch was reverted with the comment "Revert all of the splits stuff... it seems slow, and doesn't fully work"

As far as I can see nowster's code writes the .meta files out as YAML, instead of a flat list. Each split type in the YAML has the files belonging to it as a list. There is still just one artefact per chunk, but the files needed for a build are pulled out of the artefact into a sandbox according to which ones match the split names needed for the target of the build, using the lists of files per split type in the .meta file.

With morph, there is a different .meta file for each split type, which means that to obtain which splits a chunk has you need to traverse the file system, instead of just reading in a single file and letting the YAML parser do that work. On the other hand to copy the files into a sandbox, each split artifact that is needed can be copied without needing to reference the .meta files.

I'm not sure why nowster's approach would be slow or what wouldn't work with it for now.

**Comment by nowster** [comment]
On Thu, Jan 07, 2016 at 08:22:53AM -0800, Richard Dale wrote:

> nowster's branch was reverted with the comment "Revert all of the
> splits stuff... it seems slow, and doesn't fully work"

I don't remember it being much slower. The slowest step (apart from
compilation) IIRC, was the artifact compression phase.  I was
deliberately running my tests on a slow system and would have noticed
such things.

-- 
Paul Martin                                  http://www.codethink.co.uk/
Senior Software Developer, Codethink Ltd.

**Comment by devcurmudgeon** [comment]
I don't remember remember precisely but at the time i thought it was slower. However ybd elapsed time logging is more comprehensive now, so it should be pretty easy to spot if reintroducing it  does slow anything down.

the other reason i felt i had to revert was https://github.com/devcurmudgeon/ybd/issues/118

**Comment by gtristan** [comment]
@rdale, enlightening comment, this is the part which worries me:

"There is still just one artefact per chunk, but the files needed for a build are pulled out of the artefact into a sandbox according to which ones match the split names needed for the target of the build..."

This implies that during the build phase, a chunk does not depend on another chunk; but instead a chunk depends on specific artifacts (subsets of chunks).

Is this fact or fiction ? Because as far as I can see, there are no explicit references in definitions at this time which mention "This chunk depends on that artifact". From what I understand, there are artifact splitting rules which are interesting/important for the distribution (system creation) phase, I don't see however, why this complexity should be introduced during the build phase.

I have written my thoughts on this topic near the end of this email[0], essentially I feel that if artifact level selection during the build phase becomes a "thing", that opens the door to the introduction of unnecessarily complex dependency chains at build time.

Can we consider this same branch with a twist ? I.e. deferring the actual artifact splitting until system creation phase ?

[0]: http://listmaster.pepperfish.net/pipermail/baserock-dev-baserock.org/2015-November/013357.html

**Comment by devcurmudgeon** [comment]
I believe this is fixed as of 16.05
