### ISSUE TITLE
Wishlist - deploylib

### ISSUE THREAD

**Issue by devcurmudgeon** [devcurmudgeon/ybd#29]
Establish a new git repo for a project containing just the deploy extensions from morph and definitions. Let’s call it deploya unless someone can come up with a short snappy name.

EDIT: deploylib

As far as possible deploya should not depend on anything which is not available in out-of-the-box python, with the probable exception of ‘pyyaml’. Shout if there is a major functionality requirement that could be well satisfied by an existing, popular, well-behaved python module.

No command-line options. Make all of the extensions deal with input values (including config options) taken from environment variables if they are set, or a definition file if supplied (as the only parameter). The definition file takes precedence.

Submit a patch or patches for YBD to use deploya.
Stretch goal: use tbdiff properly instead of downloading whole images.

**Comment by ssssam** [comment]
I agree that the Baserock reference systems don't have any kind of deployment mechanism that YBD could use. Right now you're basically forced to use `morph deploy`, or reimplement what `morph deploy` does yourself.

I don't understand how adding a new repo into the mix of things required to build Baserock systems could be a good idea. Why not aim to have usable deployment functionality in definitions.git?

Most of the existing .write extensions could not be implemented using 'out-of-the-box Python'. For example:

rawdisk.write (creates disk images): requires mkfs.btrfs, syslinux
openstack.write: requires the same as rawdisk.write, plus OpenStack 'glance' client
virtualbox-ssh.write, kvm.write: require the same as rawdisk.write, plus 'ssh'
ssh-rsync.write, nfsboot.write, pxeboot.write: require 'ssh', and 'rsync'
initramfs.write: requires 'cpio'

Only tar.write and sysroot.write could be implemented in pure Python, really.

**Comment by ssssam** [comment]
It might make sense to spin off a new Python library for 'general utils used in Baserock deployments.' It'd be pretty easy to extract the necessary code from Morph (it's basically just the writeexts.py module). We could then say 'definitions VERSION 4 requires Baserock deployment utils v0.1.0', or some such thing. I've not fully thought through this idea yet, and in general, starting a new library with the intention of it making it reusable, stable, versioned etc. is quite a bit of work. There may be some existing library that does this already, it'd be worth looking at other projects that need to create working disk images to see how they do it and where we overlap.

**Comment by devcurmudgeon** [comment]
I don't think this should be coupled with definitions, either really, hence wanting it in its own repo. For example I think some of extensions could be used nicely with BOSH.

**Comment by devcurmudgeon** [comment]
As for the other system-level dependencies, understood. Let's just document them

**Comment by ColdrickSotK** [comment]
> No command-line options. Make all of the extensions deal with input values (including config options) taken from environment variables if they are set, or a definition file if supplied (as the only parameter).

That's almost how the write extensions currently work. They take the path of the checked out system artifact, and the `location` field from the cluster morphology as arguments, with everything else they need being passed as environment variables. It would be fairly simple to refactor them to expect to get these from the environment, but I don't see how it would be a huge benefit?

**Comment by ssssam** [comment]
I'm confused by this discussion so far, I think it might help if I update http://wiki.baserock.org/definitions/current/ to clearly document how deployment works currently.

**Comment by devcurmudgeon** [comment]
> That's almost how the write extensions currently work.

I may be wrong, but it seemed that depending on whether it's configure|check|write I had to do three different things: https://github.com/devcurmudgeon/ybd/blob/master/sandbox.py#L215

**Comment by devcurmudgeon** [comment]
> Is the hope that the Baserock project will switch to using deploya in morph too, or will this essentially be forking the write extensions?

I hope for a long life and healthy life, world peace and an end to hunger :) In this context I'm just aiming for a tidy solution that can be used by YBD and other projects (not just Baserock). So the wrinkles need to be ironed out.

**Comment by devcurmudgeon** [comment]
>  It would be fairly simple to refactor them to expect to get these from the environment, but I don't see how it would be a huge benefit?

I said
> Make all of the extensions deal with input values (including config options) taken from environment variables if they are set, or a definition file if supplied (as the only parameter). The definition file takes precedence.

So all from the environment, or from a supplied yaml file, where the yaml takes precedence. I agree this should be fairly simple.

**Comment by devcurmudgeon** [comment]
> I'm confused by this discussion so far, I think it might help if I update http://wiki.baserock.org/definitions/current/ to clearly document how deployment works currently.

I'd rather document something tidy, than the current situation which seems rather a mess, but don't let me stand in your way :)

**Comment by ssssam** [comment]
The current situation is a mess, but in order to talk about making changes to it, we need to agree on how it works at the moment, and writing such a doc has helped me understand what we actually have. I've pushed my first pass at documenting the current staus: http://wiki.baserock.org/definitions/current/

In my opinion, the "cluster" .morph file format won't have much benefit for other projects. I don't really like it's current form in Baserock, either, its only value to me is that people already use and understand it.

The "deployment extension API" is a very simple concept, I don't think it has much value outside Baserock. It's really tied to what Morph considers a "deployment" to be. Morph has this idea that a "deployment" involves taking a filesystem tree, running a bunch of arbitrary programs to make changes to the tree, then running another arbitrary program to convert and/or transfer the filesystem tree, and possibly configure its new host and instantiate it in some way. This idea of "deployment" works fine, but it's hard to find another project that considers them in the same way.

The existing pool of .configure extensions doesn't seem particularly useful outside of Baserock: most of them are programs that do simple things which would be better done with Ansible. The others are specific to certain Baserock reference systems (trove.configure, openstack-*.configure, distbuild.configure, etc.) and are of no use outside of the Baserock reference systems.

The existing pool of .write extensions, plus the morphlib.writeexts Python module they depend on, do contain some code to do non-trivial things, given a filesystem tree as input. This includes:

  - creating a cpio archive suitable for use as an initramfs 
  - creating a Btrfs-formatted disk image with a Baserock-specific layout
  - installing and configuring a SYSLINUX bootloader
  - instantiating a KVM virtual machine from a rawdisk image, on a local or remote VM host
  - instantiating a VirtualBox VM from a rawdisk image, on a local or remote VM host
  - uploading a disk image to an OpenStack 'Glance' image server
  - transferring the filesystem tree to a running Baserock reference system (or any system that uses the Baserock-specific Btrfs disk layout and contains 'system-version-manager', 'rsync' and 'baserock-system-config-sync') and making it runnable
  - transferring the filesystem tree to a pxeboot server that is configured in a certain way

Making this functionality re-usable might well be worth the effort. Although, I know there are other tools that do this sort of thing, so some research would make sense as well.

Making 'ybd' able to do exactly what `morph deploy` using the same inputs would be a different task, although it would overlap with this one. Is that the actual goal?

**Comment by richardmaw-codethink** [comment]
Decoupling deployment from morph/ybd requires at minimum changing the format to accept a filepath to a tree instead of a morphology name and tooling to be able to get a system artifact out of the cache by morphology.

We have found subtree deployment useful though, but only for writing something we already built in morph, and we haven't found setting options on the command-line for subtrees to be useful.
We could handle that by adding support for chunk builds that have an existing definition's artifacts extracted into its foo.build tree and calling out to the deploy tool.

**Comment by devcurmudgeon** [comment]
On 2015-05-21 08:49, richardmaw-codethink wrote:
> Decoupling deployment from morph/ybd requires at minimum changing the
> format to accept a filepath to a tree instead of a morphology name 
> and

Agreed.

> tooling to be able to get a system artifact out of the cache by
> morphology.

i think we're assuming that's already been done by the caller - the 
deployment gets given the tree?

> We have found subtree deployment useful though, but only for writing
> something we already built in morph, and we haven't found setting
> options on the command-line for subtrees to be useful.
>  We could handle that by adding support for chunk builds that have an
> existing definition's artifacts extracted into its foo.build tree and
> calling out to the deploy tool.

Yes, i think deploy just gets the tree, with no knowledge of what's in 
it?

**Comment by richardmaw-codethink** [comment]
> Establish a new git repo for a project containing just the deploy extensions from morph and definitions. Let’s call it deploya unless someone can come up with a short snappy name.

It's popular to name things to end in `r`. deployr possibly.
If it's expected to be a resource to other projects, then deploylib may be better.

> As far as possible deploya should not depend on anything which is not available in out-of-the-box python, with the probable exception of ‘pyyaml’. Shout if there is a major functionality requirement that could be well satisfied by an existing, popular, well-behaved python module.
> 
> No command-line options. Make all of the extensions deal with input values (including config options) taken from environment variables if they are set, or a definition file if supplied (as the only parameter). The definition file takes precedence.

I'm confused. Your first statement suggests that deploya doesn't need a program to drive the configuration or write extensions, but then the rest implies there must be, as our existing extensions already necessarily require things outside of the python standard library and pyyaml, and the API of the extensions doesn't allow for being passed a yaml document for configuration.

One of the things I like about the deployment extensions are that it is simple to write backends. It's an executable that gets passed options in the environment and command-line parameters. If we start requiring that some of its configuration comes from yaml documents, it means we can't write them as shell scripts before, which I think would be a shame, since shell scripts are an excellent domain specific language for deployments, as they are usually all about putting existing things together.

In the interest of using as little code as feasible it's totally appropriate to use domain specific language and have a driver do the common parsing operations.

If we only expect deployr to be used by python projects, we could have deployr be a library, and pass its config in via native python objects.

If we expect to call it from other languages then it doesn't yet need to be yaml, but it may as well be, as a yaml parser is easier to use than a command-line one, but it's a little perverse for its caller to parse yaml config, massage it to include file paths to stuff you've just made available, then serialise it out again to hand over to deployr.

**Comment by devcurmudgeon** [comment]
On 2015-05-21 09:23, richardmaw-codethink wrote:
>> Establish a new git repo for a project containing just the deploy
>> extensions from morph and definitions. Let’s call it deploya
>> unless someone can come up with a short snappy name.
>
> It's popular to name things to end in r. deployr possibly.
>  If it's expected to be a resource to other projects, then deploylib
> may be better.

+1 for deploylib

>> As far as possible deploya should not depend on anything which is
>> not available in out-of-the-box python, with the probable exception
>> of ‘pyyaml’. Shout if there is a major functionality requirement
>> that could be well satisfied by an existing, popular, well-behaved
>> python module.
>>
>> No command-line options. Make all of the extensions deal with input
>> values (including config options) taken from environment variables
>> if they are set, or a definition file if supplied (as the only
>> parameter). The definition file takes precedence.
>
> I'm confused. Your first statement suggests that deploya doesn't need
> a program to drive the configuration or write extensions, but then 
> the
> rest implies there must be, as our existing extensions already
> necessarily require things outside of the python standard library and
> pyyaml, and the API of the extensions doesn't allow for being passed 
> a
> yaml document for configuration.

Yes you're right. deployment is bound to depend on system-level calls 
and other scripts which may be provided.

what i'm trying to establish is that this should be 'batteries 
included' - anything it needs should be either provided in the library, 
or a widely used tool which can be expected to be available on 'normal' 
systems.

> One of the things I like about the deployment extensions are that it
> is simple to write backends. It's an executable that gets passed
> options in the environment and command-line parameters. If we start
> requiring that some of its configuration comes from yaml documents, 
> it
> means we can't write them as shell scripts before, which I think 
> would
> be a shame, since shell scripts are an excellent domain specific
> language for deployments, as they are usually all about putting
> existing things together.

Yup, i'm ok with scripts, so long as we're providing them in the box or 
they are already 'standard'

> In the interest of using as little code as feasible it's totally
> appropriate to use domain specific language and have a driver do the
> common parsing operations.

Yup.
>
> If we only expect deployr to be used by python projects, we could 
> have
> deployr be a library, and pass its config in via native python
> objects.

Well, some of the potential use-cases would not be python projects.

> If we expect to call it from other languages then it doesn't yet need
> to be yaml, but it may as well be, as a yaml parser is easier to use
> than a command-line one, but it's a little perverse for its caller to
> parse yaml config, massage it to include file paths to stuff you've
> just made available, then serialise it out again to hand over to
> deployr.

I don't know the answer to this yet, sorry. I do know that there are 
situations where deployment could be involved and all of the calling 
parameters need to be reproducible, hence the idea to take from a yaml 
file if possible.

**Comment by richardmaw-codethink** [comment]
> > tooling to be able to get a system artifact out of the cache by morphology.
> i think we're assuming that's already been done by the caller - the deployment gets given the tree?
> > We have found subtree deployment useful though, but only for writing something we already built in morph, and we haven't found setting options on the command-line for subtrees to be useful.
> > We could handle that by adding support for chunk builds that have an existing definition's artifacts extracted into its foo.build tree and calling out to the deploy tool.
> Yes, i think deploy just gets the tree, with no knowledge of what's in it?

So you're thinking of less splitting out of deployment than I was. I was expecting to remove the current cluster deployment format and have users call deployr directly. Probably replacing our cluster morphologies with a simpler format and passing the file path to the deployed tree on the command line.

**Comment by devcurmudgeon** [comment]
On 2015-05-21 09:38, richardmaw-codethink wrote:
>>> tooling to be able to get a system artifact out of the cache by
>>> morphology.
>>> i think we're assuming that's already been done by the caller -
>>> the deployment gets given the tree?
>>> We have found subtree deployment useful though, but only for
>>> writing something we already built in morph, and we haven't found
>>> setting options on the command-line for subtrees to be useful.
>>> We could handle that by adding support for chunk builds that have
>>> an existing definition's artifacts extracted into its foo.build
>>> tree and calling out to the deploy tool.
>>> Yes, i think deploy just gets the tree, with no knowledge of
>>> what's in it?
>
> So you're thinking of less splitting out of deployment than I was. I
> was expecting to remove the current cluster deployment format and 
> have
> users call deployr directly. Probably replacing our cluster
> morphologies with a simpler format and passing the file path to the
> deployed tree on the command line.

I'd be happy to see the cluster deployment format simplified, but i 
think that requires more discussion/thought?

**Comment by richardmaw-codethink** [comment]
> What i'm trying to establish is that this should be 'batteries included' - anything it needs should be either provided in the library, or a widely used tool which can be expected to be available on 'normal' systems.

I fear this requirement, as something we've analysed as being a problem which we don't handle in our current deployments is that sometimes special purpose tools **are** required, and the versions of tools available on the deploying system aren't appropriate.

The best example I can give right now is syslinux. We can't use executables we just built into our target system, as it may not be on a compatible CPU architecture, so we use the syslinux from the host system, however this is not reproducibly tracked, which resulted in us breaking syslinux with a gcc update and not noticing for a while.

This sorry state of affairs is possible because bootloader tools are developed around the idea that it'll be the running system that calls it when the bootloader is updated.

To solve this I have previously suggested that we have to sandbox our deploys as well, but with a leakier sandbox than our builds, as we need to make more resources available.

> I don't know the answer to this yet, sorry. I do know that there are
situations where deployment could be involved and all of the calling
parameters need to be reproducible, hence the idea to take from a yaml
file if possible.

What we actually need there is for the deploying program to call deploylib with the same arguments from the same inputs. Hence the calling program should be the one that takes the yaml file. It's then an implementation detail as to what we pass to deploylib, assuming we don't need users to call deploylib directly.

> I'd be happy to see the cluster deployment format simplified, but i think that requires more discussion/thought?

Agreed, especially in the nested systems case.

**Comment by devcurmudgeon** [comment]
On 2015-05-21 09:55, richardmaw-codethink wrote:
>> What i'm trying to establish is that this should be 'batteries
>> included' - anything it needs should be either provided in the
>> library, or a widely used tool which can be expected to be available
>> on 'normal' systems.
>
> I fear this requirement, as something we've analysed as being a
> problem which we don't handle in our current deployments is that
> sometimes special purpose tools ARE required, and the versions of
> tools available on the deploying system aren't appropriate.
>
> The best example I can give right now is syslinux. We can't use
> executables we just built into our target system, as it may not be on
> a compatible CPU architecture, so we use the syslinux from the host
> system, however this is not reproducibly tracked, which resulted in 
> us
> breaking syslinux with a gcc update and not noticing for a while.
>
> This sorry state of affairs is possible because bootloader tools are
> developed around the idea that it'll be the running system that calls
> it when the bootloader is updated.
>
> To solve this I have previously suggested that we have to sandbox our
> deploys as well, but with a leakier sandbox than our builds, as we
> need to make more resources available.

I agree with this, and I think YBD already does sandbox the deploys 
(this may be why some of the current deploys don't work!)

>> I don't know the answer to this yet, sorry. I do know that there are
>> situations where deployment could be involved and all of the
>> calling
>> parameters need to be reproducible, hence the idea to take from a
>> yaml
>> file if possible.
>
> What we actually need there is for the deploying program to call
> deploylib with the same arguments from the same inputs. Hence the
> calling program should be the one that takes the yaml file. It's then
> an implementation detail as to what we pass to deploylib, assuming we
> don't need users to call deploylib directly.

Yup ok.

**Comment by richardmaw-codethink** [comment]
After some further thought about this, there's another good reason to take a file path to a configuration file: It's easy to defer the running of the deploy command to another driver.

My perspective here is the installer systems. They are driven by a simple script, but their config is provided by another script.
Since the only config that the installer script actually needs is the config to pass on to the deployment, it makes a lot of sense for the driver program to provide config in a format that can just be passed on to the deploylib invocation.

So I think we draw the line with deploylib being given a subset of the config in morph's cluster morphologies, something like this:

    root-tree: /usr/lib/installer-tree
    deploy-location: /dev/sda
    deploy-type: rawdisk
    deploy-parameters:
        INITRAMFS_PATH: /boot/initramfs.gz
        KERNEL_ARGS: console=ttyS0

**Comment by ColdrickSotK** [comment]
From the above discussion, my understanding of what is wanted is this:

* A repository called **deploylib** (I assume hosted on GitHub somewhere?), containing:
    * All the configure|check|write extensions from `morph` and `definitions`, reworked to as far as possible only depend on the Python standard library.
    * A Python library containing things to help in the creation of these scripts (i.e. a standalone version of `morphlib/writeexts.py`)
    * A script to drive the use of the deployment scripts contained in deploylib, which needs some variables (at least `deploy-location`, `deploy-type`, and `root-tree`) either from the environment or from a given YAML file.
* Patches to YBD to call the aforementioned driver script rather than the deployment extensions from everywhere else.

Can you please confirm that I have understood correctly and am not missing anything here?

> The existing pool of .configure extensions doesn't seem particularly useful outside of Baserock: most of them are programs that do simple things which would be better done with Ansible. The others are specific to certain Baserock reference systems (trove.configure, openstack-*.configure, distbuild.configure, etc.) and are of no use outside of the Baserock reference systems.

I fully agree, and am interested to know what we should do regarding this. Is it worth having these in deploylib? Special thought goes to mason.configure, which copies a bunch of files from definitions into the filesystem tree, all of which aren't useful unless you're specifically deploying a Baserock Mason.

**Comment by devcurmudgeon** [comment]
On 2015-05-22 02:30, richardmaw-codethink wrote:
> After some further thought about this, there's another good reason to
> take a file path to a configuration file: It's easy to defer the
> running of the deploy command to another driver.
>
> My perspective here is the installer systems. They are driven by a
> simple script, but their config is provided by another script.
>  Since the only config that the installer script actually needs is 
> the
> config to pass on to the deployment, it makes a lot of sense for the
> driver program to provide config in a format that can just be passed
> on to the deploylib invocation.
>
> So I think we draw the line with deploylib being given a subset of 
> the
> config in morph's cluster morphologies, something like this:
>
> root-tree: /usr/lib/installer-tree
> deploy-location: /dev/sda
> deploy-type: rawdisk
> deploy-parameters:
>  INITRAMFS_PATH: /boot/initramfs.gz
>  KERNEL_ARGS: console=ttyS0

Looks good to me +1

**Comment by richardmaw-codethink** [comment]
On Fri, May 22, 2015 at 05:21:24AM -0700, Adam Coldrick wrote:
> > The existing pool of .configure extensions doesn't seem particularly useful
> > outside of Baserock: most of them are programs that do simple things which
> > would be better done with Ansible. The others are specific to certain
> > Baserock reference systems (trove.configure, openstack-*.configure,
> > distbuild.configure, etc.) and are of no use outside of the Baserock
> > reference systems.
> 
> I fully agree, and am interested to know what we should do regarding this. Is
> it worth having these in deploylib? Special thought goes to mason.configure,
> which copies a bunch of files from definitions into the filesystem tree, all
> of which aren't useful unless you're specifically deploying a Baserock Mason.

That sounds like justification for being able to provide an extension search
path to deploylib to me.

**Comment by ColdrickSotK** [comment]
> That sounds like justification for being able to provide an extension search
path to deploylib to me.

That sounds like a sensible solution.

**Comment by devcurmudgeon** [comment]
On 2015-05-22 05:21, Adam Coldrick wrote:
> 	* A repository called DEPLOYLIB (I assume hosted on GitHub

Yup. https://github.com/CodethinkLabs/deploylib

> somewhere?), containing:
>
>  	* All the configure|check|write extensions from morph and
> definitions, reworked to as far as possible only depend on the Python
> standard library.

+ calls to ssh etc

>  	* A Python library containing things to help in the creation of
> these scripts (i.e. a standalone version of morphlib/writeexts.py)

Why would this be separate from deploylib?

>  	* A script to drive the use of the deployment scripts contained in
> deploylib, which needs some variables (at least deploy-location,
> deploy-type, and root-tree) either from the environment or from a
> given YAML file.

I think so

>  	* Patches to YBD to call the aforementioned driver script rather
> than the deployment extensions from everywhere else.

Yup

**Comment by ColdrickSotK** [comment]
> Why would this be separate from deploylib?

I meant standalone from morphlib, I was planning for this to live in deploylib.

> + calls to ssh etc

Sure, things like that are unavoidable. I mostly meant to get rid of any unnecessary non-standard Python dependencies.

**Comment by ColdrickSotK** [comment]
> Yup. https://github.com/CodethinkLabs/deploylib

I don't seem to have push access for that repository. Is there any chance you can grant it? Thanks!

**Comment by devcurmudgeon** [comment]
On 2015-05-22 07:22, Adam Coldrick wrote:
>> Yup. https://github.com/CodethinkLabs/deploylib [1]
>
> I don't seem to have push access for that repository. Is there any
> chance you can grant it? Thanks!

Done. I've added ssssam and richard too, just in case

**Comment by devcurmudgeon** [comment]
On 2015-05-22 06:17, Adam Coldrick wrote:
>> Why would this be separate from deploylib?
>
> I meant standalone from morphlib, I was planning for this to live in
> deploylib.
>
>> * calls to ssh etc
>
> Sure, things like that are unavoidable. I mostly meant to get rid of
> any unnecessary non-standard Python dependencies.

Perfect

**Comment by devcurmudgeon** [comment]
So the deploylib concept is now implemented in definitions.git
