### ISSUE TITLE
wishlist - platform-independent sandbox library

### ISSUE THREAD

**Issue by devcurmudgeon** [devcurmudgeon/ybd#32]
Currently YBD uses the same linux-user-chroot approach for sandboxing builds as Morph (but the logic has been simplified, here).
The aim of this project is to provide a new standalone python library (ideally in a single python file) which

- detects which platform it is running on (initially Linux and MacOS, then optionally BSD, possibly ultimately Windows)
- executes a provided command, with args 
- using whatever this platform’s default equivalent of chroot is in the provided directory tree
- and applying some set of further constraints (eg the binds etc) if possible on this platform
and reporting success/fail in the normal unix way

Confirm that the library works as expected on Linux and MacOS. Submit patches for YBD to use this new library function instead of the current approach in sandbox.run_sandboxed

**Comment by ssssam** [comment]
How does MacOS fit into the picture here? From the point of view of building the Baserock reference systems, MacOS is a new architecture, as its kernel has a different syscall interface to Linux. Software native-compiled in a chroot on MacOS would need to support the MacOS syscall ABI for it to work in the chroot, and would /only/ run under a MacOS kernel. To deploy a full system, the system would need to include the MacOS kernel instead of Linux. (I'm not sure if that's possible or not, I don't know which bits of MacOS X are open source, or redistributable)

Is your goal to add support to 'ybd' for building software that will run on MacOS? If so, having a way of sandboxing builds on OSX, plus a way of differentiating x86_64-with-macos-kernel from x86_64-with-linux-kernel, is probably all that's needed. If your goal is to build Linux systems with 'ybd' running on MacOS, it'd effectively be cross-compilation and I think much more work would be needed.

**Comment by devcurmudgeon** [comment]
ultimately the goal is *do all the things* :) 

but for now this item is just about providing the ability to sandbox a command, cross-platform, as a generic soln (for initial use on YBD, but maybe also non-baserock projects). maybe there's already something  that already does this, but i couldn't find it.

i agree, actually doing such builds will lead us inevitably towards the pit-of-despair called cross-compile :)

**Comment by ssssam** [comment]
OK. I had a look for existing APIs that might do this. I worked on the assumption that 'containers' and 'sandboxes' are often interchangable concepts.

There are some that are Linux-specific, which I guess aren't suitable: [lxc](https://linuxcontainers.org/), [systemd-nspawn](http://www.freedesktop.org/software/systemd/man/systemd-nspawn.html), and [xdg-app](https://github.com/alexlarsson/xdg-app) spring to mind. And linux-user-chroot of course.

Docker [already supports multiple 'execution drivers'](https://blog.docker.com/2014/03/docker-0-9-introducing-execution-drivers-and-libcontainer/), so theoretically could be used as a cross-platform sandbox tool. It's a big project though and I can't see any sign that they care much about different 'execution drivers' (no sign of an OSX one, in particular), so trying to reuse Docker for this would probably be an exercise in pissing in the wind.

That leaves the CoreOS ['App container spec'](https://github.com/appc/spec), which aims to be some generic way of specifying containers. Wouldn't it be great if we could use this API instead of having to maintain our own? I couldn't find an OSX implementation of 'appc', but [the spec](https://github.com/appc/spec/blob/master/SPEC.md) seems lightweight enough, and I guess we could simply use chroot() on OSX as a 'good enough' implementation for the time being.

**Comment by ssssam** [comment]
note we'd still have to write the library to actually do 'appc', at least for OSX (for Linux we might be able to reuse 'rkt' or something else), but it seems to me that having ybd staging areas be specified using an established format that other tools understand would be a good thing.

**Comment by devcurmudgeon** [comment]
On 2015-05-20 10:04, Sam Thursfield wrote:
> OK. I had a look for existing APIs that might do this. I worked on 
> the
> assumption that 'containers' and 'sandboxes' are often interchangable
> concepts.
>
> There are some that are Linux-specific, which I guess aren't 
> suitable:
> lxc [1], systemd-nspawn [2], and xdg-app [3] spring to mind. And
> linux-user-chroot of course.
>
> Docker already supports multiple 'execution drivers' [4], so
> theoretically could be used as a cross-platform sandbox tool. It's a
> big project though and I can't see any sign that they care much about
> different 'execution drivers' (no sign of an OSX one, in particular),
> so trying to reuse Docker for this would probably be an exercise in
> pissing in the wind.

Not docker, or anything at that scale. I think this needs to be as 
minimal as possible, unless we establish that minimal is *not* possible.

> That leaves the CoreOS 'App container spec' [5], which aims to be 
> some
> generic way of specifying containers. Wouldn't it be great if we 
> could
> use this API instead of having to maintain our own? I couldn't find 
> an
> OSX implementation of 'appc', but the spec [6] seems lightweight
> enough, and I guess we could simply use chroot() on OSX as a 'good
> enough' implementation for the time being.

Sounds worth investigating, at least.

**Comment by richardmaw-codethink** [comment]
> The aim of this project is to provide a new standalone python library (ideally in a single python file) which:

I saw that one of your other issues is that it requires root privileges. You won't get both on Linux. You need a helper setuid root binary to be able to set up the environment before it can be safe enough to run unprivileged code in.

> *   using whatever this platform’s default equivalent of chroot is in the provided directory tree
>     and applying some set of further constraints (eg the binds etc) if possible on this platform and reporting success/fail in the normal unix way

This would be a significant reduction in build isolation, since only in Plan9 is everything part of the filesystem namespace.

> Confirm that the library works as expected on Linux and MacOS. Submit patches for YBD to use this new library function instead of the current approach in sandbox.run_sandboxed

> ultimately the goal is do all the things :)

> i agree, actually doing such builds will lead us inevitably towards the pit-of-despair called cross-compile :)

I think we would have to be *committed* to supporting cross compilation of everything in future for this to be a worthy approach, otherwise it will be written and likely sit unused until it bit-rots.
I think supporting cross-compilation on Linux would be a better first step towards that goal.

> OK. I had a look for existing APIs that might do this. I worked on the assumption that 'containers' and 'sandboxes' are often interchangable concepts.

They are not, but containers are a way to do some sandboxing. An alternative approach that may be of interest is Google's http://bazel.io/faq.html tool, which appears to trap any accesses that aren't explicitly allowed.

> edit: https://github.com/appc/spec/blob/master/SPEC.md#app-container-executor is the only bit of the spec we actually need to care about

The app container spec actually requires a superset of the functionality we need to build, as it requires *all* of the tree be writable, when we only need a subset of it to be, which requires overlay support to be performant.

Build tools don't generally *need* write access to every part of the system, so if we were to use this spec, we would need to extend it in a way that is not compatible with other implementations, unless we put the effort in to upstream the writability whitelist.

> note we'd still have to write the library to actually do 'appc', at least for OSX (for Linux we might be able to reuse 'rkt' or something else), but it seems to me that having ybd staging areas be specified using an established format that other tools understand would be a good thing.

Me too, I'd rather we re-used existing libraries if they suit our purposes.

Given the variety of different capabilities of sandboxing mechanisms, the only thing we can commonly describe across all of them is "everything you can", or implicitly be "everything you need to be able to build with" which stops it being a general purpose sandboxing library.

Given the degenerate case for all Unix-like systems is `chroot`, I'm not sure it's worth putting the cross platform indirection in another library.
There may be some value in moving the linux-user-chroot wrapping out into another library so the code can be shared between multiple projects, but platform detection is easy enough.

**Comment by devcurmudgeon** [comment]
My problems with the current scheme (apart from the fact that i still don't understand what the code does) are
a) it requires root
b) it only works on Linux
Are you saying that neither of these problems are not solvable?

**Comment by richardmaw-codethink** [comment]
On Sat, May 23, 2015 at 03:24:36PM -0700, Paul Sherwood wrote:
> My problems with the current scheme (apart from the fact that i still don't understand what the code does) are
> a) it requires root
> b) it only works on Linux
> Are you saying that neither of these problems are not solvable?

The double negatives here are confusing me a little.

I believe we can solve either with some effort, but not both, as the degenerate
case we can assume is chroot, which requires root privileges and is not
sufficiently safe sandboxing.

There's two ways to solve sandboxing on Linux without root:

1.  A privileged helper program
2.  Enabling unprivileged user namespaces in the kernel

The second option is not feasible at least short-term because it is not
sufficiently mature to be considered secure, and we also support chroots, which
further extends the period, since we would need to wait for common distros to
enable it.

We already do the first option. The reason we currently cannot build without
root in morph is that we expect to be able to extract device nodes from cached
artifact tarballs.

This is not insurmountable, as we could instead bind-mount a safe subset of the
device nodes into the build sandbox.


The privileged helper program is an approach available to Unixes or other
Unix-likes, but this is only sufficiently safe with linux-user-chroot because
of all the effort it goes through to prevent sandboxed commands being able to
break out including:

1.  Dropping down to a lower privilege level after the sandbox is set up
2.  Preventing privileges from being re-gained by marking the filesystem mount
    such that setuid binaries may not be executed.

This prevents escaping the sandbox through the channels which are accepted as
proper APIs that just happen to be usable to escape sandboxes, and instead
leaves the more insidious privilege escalation vulnerabilities which are much
harder to use.

**Comment by devcurmudgeon** [comment]
On 2015-05-26 02:29, richardmaw-codethink wrote:
> On Sat, May 23, 2015 at 03:24:36PM -0700, Paul Sherwood wrote:
>  > My problems with the current scheme (apart from the fact that i
> still dont understand what the code does) are
>  > a) it requires root
>  > b) it only works on Linux
>  > Are you saying that neither of these problems are not solvable?
>
>  The double negatives here are confusing me a little.

Sorry, i don't know what i was thinking :)

**Comment by ssssam** [comment]
The 'sandboxlib' library now exists at https://github.com/CodethinkLabs/sandboxlib and https://pypi.python.org/pypi/sandboxlib

Next I'll look at getting the 'chroot' backend usable by YBD.

As for building as non-root: I think that's a complicated problem that needs to be treated as a separate issue. I have done some work towards it but am not really confident about any approach so far.

**Comment by devcurmudgeon** [comment]
Great stuff, @ssssam, thanks!

**Comment by ssssam** [comment]
Pull request #62 adds support for using chroot() instead of 'linux-user-chroot' when the latter is not available.

**Comment by ssssam** [comment]
I had a bit of a play with YBD on Mac OS X to see what is possible.

With one patch <https://gerrit.baserock.org/#/c/815/> I managed to build stage1-binutils and stage1-gcc from the Baserock reference system definitions. The build of stage2-linux-api-headers then failed due to some missing header file, which is not a big surprise.

In order to get further, we'd need to build a libc that worked on Mac OS X. I tried GLibc 2.21 but it doesn't configure:

    *** The GNU C library is currently not available for this platform.
    *** So far nobody cared to port it and if there is no volunteer it
    *** might never happen.  So, if you have interest to see glibc on
    *** this platform visit
    ***	http://www.gnu.org/software/libc/porting.html
    *** and join the group of porters

A bit of searching for 'glibc darwin port' turns up a project from 2001 but nothing promising.

It turns out [Apple's Libc is open source](http://www.opensource.apple.com/tarballs/Libc/), so I had a go at building that. I think it's possible, but it's not trivial. For me, it failed because of headers missing in /System/include/.... I found [some instructions](http://www.mulle-kybernetik.com/weblog/2011/how_to_build_libobjc_for_os_x.html) that suggests I could download six other tarballs and assemble a suitable build environment. https://stackoverflow.com/questions/7592069/how-to-build-apples-opensource-libc might also be useful. I think theoretically it'd be feasible to get a Baserock chroot built and working on OS X, but without cross-compilation support in YBD we couldn't build any useful Linux systems on OS X.

**Comment by devcurmudgeon** [comment]
On 2015-06-09 15:52, Sam Thursfield wrote:
> I had a bit of a play with YBD on Mac OS X to see what is possible.
>
> With one patch https://gerrit.baserock.org/#/c/815/ [1] I managed to
> build stage1-binutils and stage1-gcc from the Baserock reference
> system definitions. The build of stage2-linux-api-headers then failed
> due to some missing header file, which is not a big surprise.
>
> In order to get further, we'd need to build a libc that worked on Mac
> OS X. I tried GLibc 2.21 but it doesn't configure:
>
> *** The GNU C library is currently not available for this platform.
> *** So far nobody cared to port it and if there is no volunteer it
> *** might never happen. So, if you have interest to see glibc on
> *** this platform visit
> *** http://www.gnu.org/software/libc/porting.html
> *** and join the group of porters
>
> A bit of searching for 'glibc darwin port' turns up a project from
> 2001 but nothing promising.
>
> It turns out Apple's Libc is open source [2], so I had a go at
> building that. I think it's possible, but it's not trivial. For me, 
> it
> failed because of headers missing in /System/include/.... I found 
> some
> instructions [3] that suggests I could download six other tarballs 
> and
> assemble a suitable build environment.
> 
> https://stackoverflow.com/questions/7592069/how-to-build-apples-opensource-libc
> [4] might also be useful. I think theoretically it'd be feasible to
> get a Baserock chroot built and working on OS X, but without
> cross-compilation support in YBD we couldn't build any useful Linux
> systems on OS X.

good to know, thanks!

**Comment by devcurmudgeon** [comment]
I'm calling this closed - there's a separate issue #24 for ybd still requiring root
